import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
demo.c
""")

path = [cwd + 'include/autoquad', 
    cwd + 'include'
    cwd + 'include/common']

#CPPDEFINES = ['USE_STDPERIPH_DRIVER', rtconfig.STM32_TYPE]
CPPDEFINES = ['USE_STDPERIPH_DRIVER']
group = DefineGroup('mavlink_head', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
